"""add index

Revision ID: 480312c0e5a4
Revises: f5f718b25c5d
Create Date: 2024-01-12 22:53:39.290719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480312c0e5a4'
down_revision: Union[str, None] = 'f5f718b25c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_ip_address'), 'sessions', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_ip_address'), table_name='sessions')
    # ### end Alembic commands ###
